### ISSUE TITLE
suppress error output to terminal

### ISSUE THREAD

**Issue by muralikodali** [magnouvean/rofi-mpc#1]
rofi-mpc is giving output to terminal, if we get out of  any uncompleted task.

is there any option to supress output to terminal?

```
Traceback (most recent call last):
  File "/home/xxxx/Downloads/rofi-mpc/./rofi-mpc", line 131, in <module>
    res = mpc_command_result(opts_data)
  File "/home/xxxx/Downloads/rofi-mpc/./rofi-mpc", line 48, in mpc_command_result
    raise Exception("Rofi exited before a selection was made")
Exception: Rofi exited before a selection was made
```

**Comment by magnouvean** [comment]
Thanks for the issue. At the moment there is not, but I agree that this should definitely be a command line option. When I have time I'll add a command line flag (`-q` and `--quiet`), and make the output prettier without the flag.

**Comment by magnouvean** [comment]
This should now be implemented with https://github.com/magnouvean/rofi-mpc/pull/2, simply use the `-q` or `--quiet` flags. Also without these flags the output should be much prettier! I will probably add a 1.0.2 release after this :). I'm closing this, but feel free to reopen if there are any issues regarding this still :)
